### PR TITLE
fix rockspec url

### LINKED ISSUE #8: source url unavailable
the download link in the rockspec https://github.com/ittner/lua-iconv/blob/b761918588736348698eb060a3a490f448786f01/lua-iconv-7-1.rockspec#L9C10-L9C74 is a 404. It breaks my script that autogenerates nix code. 

Is it possible to fix the rockspec to point at an existing archive ?

### PR DESCRIPTION
**Pull request by teto**
Fixes #8

### CODE REVIEW

**Comment by alerque** [comment]
Can I suggest you add another commit with the *previous* stable published rockspec version? Exactly how it is (broken or not) would be preferred. That just gives a way to diff from that to the current one to compare. Useful for PR review but also for later debugging other things. You can actually add as many back-releases of published rockspecs as you like, my personal preference is to keep all of them in the rockspecs folder for posterity. It does make it easier down the road to trace changes. But even if you don't do many of them, the last published one would be useful.

**Comment by teto** [comment]
maybe you missed it because it was a renaming but I did move from the main folder to "rockspecs/" the currently broken rockspec. Following up on your remark I've added the 6.1 version

**Comment by alerque** [comment]
Yes I probably skimmed the diff too fast.

**Review by alerque — APPROVED** [review]
LGTM.

**Comment by alerque** [comment]
And now we cross our fingers and see if [this CI run](https://github.com/lunarmodules/lua-iconv/actions/runs/6442931263) ends in a successful publish to LuaRocks ;-)

**Comment by teto** [comment]
I've been waiting for this for the past few months. Crossing fingers indeed xD

**Comment by teto** [comment]
and it failed xD ! we dont see the command executed which is sad. I suppose it's a luarocks upload. Not sure why it needs a folder, is that for a rock ? what If I only care about rockspecs ? https://github.com/lunarmodules/lua-iconv/actions/runs/6442931263/job/17494299938#step:8:13

**Comment by alerque** [comment]
Nope. I forgot, the way it is setup right now to publish a stable version there also needs to be a matching tag in the Git repo. On the `master` branch locally can you `git tag 7.0.0` on the merge commit this PR produced, then `git push --tags`? Or I can do the honours if you don't want to.

**Comment by alerque** [comment]
In order to verify that the rockspec actually works, it has to have the Git tag because without it the URL mentioned in the rockspec as where to download sources doesn't exist.

**Comment by teto** [comment]
I had already created the tag but before the merge so maybe it's missing some file. I'll let you do the honour this time as you know more what needs to be done.

**Comment by alerque** [comment]
Why the deuce does the GH releases interface show *me* as the one having tagged `v7.0.0`. I have no recollection of doing that and you just say you *did* do it! Why is GH contradicting both of us about our own actions?

image

**Comment by teto** [comment]
I pushed the tag on your commit, github UI is just lying xD

**Comment by alerque** [comment]
I see. The commit is mine and it has no author info on the tag itself so it just makes stuff up. Great.

In any case 8e19fde5f3b78b3b8f3a78944322d4f121edfbb0 has fixed your issue, see `source.dir` in [Rockspec Format](https://github.com/luarocks/luarocks/wiki/Rockspec-format#build-rules) for details. GitHub allows downloads of source archives with any arbitrary name you want if you ask for the tag name the some valid archive filename. This format means the archive filename and the directory that it extracts to match.

**Comment by alerque** [comment]
I'll just note for the record that editing a rockspec like I just did only works *before* it successfully publishes. Once it is published to LuaRocks it should be considered immutable (future deploy CI jobs would fail anyway) and if something needs fixing it should be done with a new $ROCKREL bump.

**Comment by teto** [comment]
I was trying to run luarocks nix on lua-iconv but it still fails because the rockspecs urls point at a wrong uri:
```
nix-prefetch-url https://github.com/downloads/ittner/lua-iconv/lua-iconv-7.tar.gz
error: unable to download 'https://github.com/downloads/ittner/lua-iconv/lua-iconv-7.tar.gz': HTTP error 404

       response body:

       Not Found

```

And the uploaded rockspecs are absent from the rockspec folder too https://luarocks.org/modules/lunarmodules/lua-iconv/7-3 . I am not sure how to fix that properly, if you dont mind having a look

**Comment by alerque** [comment]
@teto This appears to be a bug on LuaRocks.org itself and potentially a related one in the `luarocks` app itself. I'll look into reporting this after mentioning here that your problem is that you're not working with the latest version. The latest release with the correct URL in the rockspec and the rockspec file where it belongs is 7.0.0-2, tagged in Git as v7.0.0.

The src URL listed in the published [lua-iconv-7.0.0-2.rockspec](https://luarocks.org/manifests/lunarmodules/lua-iconv-7.0.0-2.rockspec) is https://github.com/lunarmodules/lua-iconv/archive/v7.0.0/lua-iconv-7.0.0.tar.gz which is correct and works.

I was somewhat surprised to find `luarocks install lua-icon` works to install `7-3`, but the reason is it uses the published src.rock instead of downloading the published rockspec and fetching the sources mentioned in the manifest (which is where your broken link is originating).

I believe the *real* fix is to make sure LuaRocks.org and `luarocks` do a better job of sorting version numbers so 7.0.0 is newer than 7, but that might need long term adjustments. The short term workaround is probably tag a new bigger version number.

**Comment by alerque** [comment]
I checked out the source of `luarocks` and the current sorting is deliberate. I disagree that it is the best way, but it intentionally discards segments not present in both strings. In other words `7` and `7.0.0` evaluate to the same version, and the rockrel ends up getting them in the "wrong" order for us. I think we should bump the rockrel to `-4` to get past this problem.

**Comment by alerque** [comment]
I just pushed a `-4` rockrel so [LuaRocks.org](https://luarocks.org/modules/lunarmodules/lua-iconv) turns up the newest release as one that has a valid URL in the rockspec, and `luarocks install` should find it as well.

**Pull request merged**
